### ISSUE TITLE
Use https to contact 3scale

### ISSUE THREAD

**Issue by davel** [3scale/3scale_ws_api_for_perl#6]
Further to https://github.com/3scale/3scale_ws_api_for_perl/pull/5#discussion_r94447563 we should be using https to contact 3scale, as API keys are potentially valuable. We should switch to persistent connections to minimise the performance impact.

**Comment by slobo** [comment]
Would this be enough to have it keep the connection alive?
```perl
$self->{ua} = LWP::UserAgent->new( agent => $agent_string, keep_alive => 1 );
```

From LWP::UserAgent docs:
> If the `keep_alive` option is passed in, then a `LWP::ConnCache` is set up [...]. The keep_alive value is passed on as the `total_capacity` for the connection cache.

Or is the fear that doesn't work as advertised? Since this module only supports (non-rotatable?) all mighty and powerful `provider_key`, https seems like a very good idea...

**Comment by davel** [comment]
Yes, that should do it. I have never been sure as to whether or LWP::ConnCache does the right thing across a fork. I usually do something like,
```
sub _ua {
    state $pid = $$;
    state $ua;
    if ($pid != $$) {
        $pid = $$;
        $ua = undef;
    }
    $ua ||= LWP::UserAgent->new( agent => $agent_string, keep_alive => 1 );
    return $ua;
}
```

**Comment by slobo** [comment]
Hm, interesting point, definitely something to watch out for. 

Can you expand a bit on situations in which you would `fork` after setting up an instance of `Net::ThreeScale::Client`? I just assumed that with Catalyst/Mojo I would setup one instance for each pre-forked worker and wouldn't do any more forking after that...

Thanks

**Comment by davel** [comment]
There is no guarantee that this library code is being called from a sensible Catalyst/Mojo environment, or even from an HTTP request.

**Comment by slobo** [comment]
Makes sense, thanks.
